export const ActionTypes = {
    FETCH_POSTS: 'FETCH_POSTS',
    RECEIVED_POSTS: 'RECEIVED_POSTS',
    FETCH_POSTS_DONE: 'FETCH_POSTS_DONE',
    FILTER_UPDATE: 'FILTER_UPDATE',
    RECEIVE_COMMENTS: 'RECEIVE_COMMENTS',
    ADD_POST: 'ADD_POST',
    UPVOTE_POST: 'UPVOTE_POST',
    DOWNVOTE_POST: 'DOWNVOTE_POST',
    ADD_COMMENT: 'ADD_COMMENT',
    UPVOTE_COMMENT: 'UPVOTE_COMMENT',
    DOWNVOTE_COMMENT: 'DOWNVOTE_COMMENT'
}